name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  CI:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Creer fichier .env
        run: |
          echo "DB_HOST=localhost" > .env
          echo "DB_PORT=3306" >> .env
          echo "DB_NAME=test" >> .env
          echo "DB_USER=root" >> .env
          echo "DB_PASS=" >> .env
          echo "REDIS_HOST=localhost" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_DB=0" >> .env

      - name: Setup database
        run: |
          mysql -u root -e "CREATE DATABASE IF NOT EXISTS test;"
          mysql -u root test < db.init

      - name: Tests
        run: |
          python -m pytest src/tests/test_store_manager.py -q