name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: [self-hosted, linux, x64]
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: labo02_db
          MYSQL_USER: labo02
          MYSQL_PASSWORD: labo02
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev default-libmysqlclient-dev build-essential
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Au cas où pytest n'est pas dans requirements.txt
          
      - name: Create .env file
        run: |
          echo "DB_HOST=127.0.0.1" > .env
          echo "DB_PORT=3306" >> .env
          echo "DB_NAME=labo02_db" >> .env
          echo "DB_USER=labo02" >> .env
          echo "DB_PASS=labo02" >> .env
          echo "REDIS_HOST=127.0.0.1" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_DB=0" >> .env

      - name: Wait for services
        run: |
          sleep 30  # Attendre que MySQL et Redis démarrent
          
      - name: Initialize database
        run: |
          mysql -h 127.0.0.1 -u labo02 -plabo02 labo02_db < db.init
        
      - name: Run tests
        run: |
          cd src && python -m pytest tests/test_store_manager.py -v
        
      - name: Run tests (fallback)
        if: failure()
        run: |
          python -m pytest src/tests/test_store_manager.py -v || python3 -m pytest src/tests/test_store_manager.py -v